### PR TITLE
Popup

### PR DESCRIPTION
**Pull request by leonardodiasb**
Created JS function to generate HTML works section based in an object stored in JS file.
Created JS function to generate HTML popup section based in the project container clicked.
Created JS function to remove popup section when the button X is clicked.
Added some CSS styles for the popup section.
Deleted HTML works section.

### CODE REVIEW

**Review by Shaher-11 — CHANGES_REQUESTED** [review]
#### Hello @leonardodiasb, 

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [x] Reduce the popup size on the desktop so it does not overlap the screen.
- [ ] Reduce popup's buttons height on the mobile.
- [x] See screenshots below:point_down:

#### Desktop size

wrong1

#### Bottons on mobile
wrong2


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

**Comment by leonardodiasb** [comment]
> #### Hello @leonardodiasb,
> ### Great job so far!
> You have been doing an incredible job on the project so far👏👏
> The project is very well structured😃😃
> However, we still need to make a few changes to get the project approved💪
> 
> ## Required Changes ♻️
> * [ ]  Reduce the popup size on the desktop so it does not overlap the screen.
> * [ ]  Reduce popup's buttons height on the mobile.
> * [ ]  See screenshots below👇
> 
> #### Desktop size
> wrong1
> 
> #### Bottons on mobile
> wrong2
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> Happy Coding!👏👏👏

Thanks for the review Shaher. I was trying to follow the template style and the popup image on the desktop looks like this. It looks like it overlaps the screen, so if I try to reduce the popup size too much for the desktop it will look too small with a lot of empty space on the sides.

**Review by Shaher-11 — CHANGES_REQUESTED** [review]
#### Hello @leonardodiasb  

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The functionality works great:smiley::smiley:
However, we still need to make the few style changes  requested in the last code review to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Check the screenshots below:point_down:

#### Original Project popup on desktop

right1

#### Original Project popup on mobile

right2


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

**Review by Shaher-11 — APPROVED** [review]
#### Hello @leonardodiasb ,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle::muscle:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Pull request merged**
